---
- name: Install Django Development Environment
  hosts: all
  user: vagrant
  gather_facts: no
  vars:
    zsh_theme: cloud
  # roles are specified in Vagrantfile (ansible.extra_vars)
  roles:
    - { role: common, when: "'common' in roles " }
    - { role: python, when: "'python' in roles " }
    - { role: mysql, when: "'mysql' in roles " }
    - { role: postgres, when: "'postgres' in roles " }
    - { role: elasticsearch, when: "'elasticsearch' in roles " }
    - { role: nodejs, when: "'nodejs' in roles ", npm_packages: npm_packages }
    - { role: redis, when: "'redis' in roles " }
